apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 3
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: w-gcp-container
        image: gcr.io/wallenius-k8s/w-gcp
        ports:
        - containerPort: 8080
