apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-rc-v2
  labels:
    name: frontend
spec:
  replicas: 3
  selector:
    name: frontend
    version: v2
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend-app
        image: gcr.io/wallenius-k8s/frontend-app
        ports:
        - containerPort: 8080
